version: '3'

services:
  django:
    build: ./tradesparkChallangeDjango
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tradesparkChallangeDjango:/app
    ports:
      - "8000:8000"

  angular:
    build: ./tradesparkChallengeAngular
    volumes:
      - ./tradesparkChallengeAngular/src:/app/src
      - /app/node_modules
    ports:
      - "4200:4200"
